// Generated by https://quicktype.io

export interface AuthResponse {
  token: string;
  user: User;
}

export interface User {
  id: string;
  name: string;
  lastName: string;
  userPermission: string;
  userType: string;
  profilePicUrl?: string;
}
